media:
  name: images
  label: Images
  input: images
  output: /images
  extensions: [png, jpg, jpeg, webp, svg]

content:
  - name: homepage
    label: Home Page
    type: file
    path: index.html
    format: raw
    fields:
      - name: body
        label: Raw HTML Content
        type: text
